apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: demos
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: mqttbroker-deployment
    namespace: demos
    labels:
      app: mqttbroker
  spec:
    selector:
      matchLabels:
        app: mqttbroker
    template:
      metadata:
        namespace: demos
        labels:
          app: mqttbroker
      spec:
        containers:
        - name: mqttbroker
          image:  eclipse-mosquitto:latest
          ports:
          - containerPort: 80
          imagePullPolicy: Never
          resources:
            requests:
              memory: "512M"
              cpu: "0.5"
            limits:
              memory: "1G"
              cpu: "1"
          volumeMounts:
              - name: mosquitto-conf
                mountPath: /mosquitto/config
        volumes:
          - name: mosquitto-conf
            configMap:
               name: mosquitto-config-file
          # volumeMounts:
          #   - mountPath:  "/mosquitto"
          #     name: mqttbroker-pv-storage
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mosquitto-config-file
  data:
    mosquitto.conf: |
      log_dest stdout
      log_type all
      log_timestamp true
      listener 80
      protocol websockets
      allow_anonymous true

# service
- apiVersion: v1
  kind: Service
  metadata:
    name: mqttbroker-service
    namespace: demos
  spec:
    selector:
      app: mqttbroker
    ports:
      - name: websocket
        port: 80 
        targetPort: 80
        protocol: TCP 
# Ingress
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: mqttbroker-ingress
    namespace: demos
  spec:
   ingressClassName: nginx
   rules:
    - host: kubernetes.docker.internal
      http:
       paths:
        - path: /
          pathType: Prefix
          backend:
           service: 
             name: mqttbroker-service
             port:
              number : 80

        